steps:
  - name: 'gcr.io/cloud-builders/git'
    args: 
      - ['clone', 'https://github.com/GoogleCloudPlatform/cloud-builders']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'git'
    args:
      - ['clone', 'https://quanta-bmc-private.googlesource.com/meta-gsz']

options:
  logging: CLOUD_LOGGING_ONLY
