steps:
  - name: 'gcr.io/cloud-builders/git:latest'
    args: ['clone', 'https://gbmc-internal.googlesource.com/gbmc']
  - name: 'gcr.io/cloud-builders/git:latest'
    args: ['clone', 'https://quanta-bmc-private.googlesource.com/meta-gsz']
options:
  logging: CLOUD_LOGGING_ONLY
