steps:
  - name: 'sudo'
    args: 
      - git
      - clone
      - https://gbmc-internal.googlesource.com/gbmc
  - name: 'gcr.io/cloud-builders/git:latest'
    args: ['clone', 'https://quanta-bmc-private.googlesource.com/meta-gsz']

serviceAccount: 'projects/gbmc-builders/serviceAccounts/gbmc-presubmit@gbmc-builders.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY
