steps:
  - name: 'gcr.io/gbmc-builders/gbmc-firmware-builder:latest'
    args: 
      - sudo
      - python
      - clone.py

serviceAccount: 'projects/gbmc-builders/serviceAccounts/gbmc-presubmit@gbmc-builders.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY