steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'git'
    args: ['clone', 'https://source.developers.google.com/p/gbmc-builders/r/meta-gsz']
options:
  logging: CLOUD_LOGGING_ONLY
